version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=spring_app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
    volumes:
      - /data/mysql
  auth-server-container:
    image: auth-server
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker-container:3306/spring_app_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=test123
    ports:
      - 8087:8080
    volumes:
      - /data/auth-server
  resource-server-container:
    image: resource-server
    build:
      context: ../resource-server
      dockerfile: Dockerfile
    environment:
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=http://auth-server-container:8080/validateUser
      - SERVER_PORT=8080
    ports:
      - 9000:8080
    volumes:
      - /data/resource-server
